### ISSUE TITLE
Add topics so your project is listed.

### ISSUE THREAD

**Issue by justinmeiners** [jsawruk/lc3-vm#2]
Hello,

I hope you enjoyed our tutorial.
Previously your project was listed on the page,
but since we have received so many we are changing the tutorial
to link to topics and languages on GitHub, instead of listing them all individually.

If you want your project to appear in the list, please add the GitHub topic "lc3".

Thanks for your work!
Justin Meiners (lc3-vm author)

**Comment by jsawruk** [comment]
Added Github topic. Will revisit tutorial to update repo.

Thank you for creating your tutorial; I learned a lot about VMs.
